#端口号
server:
  port: 8083
#nacos的注册地址和配置地址
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
    #开启sentinel
    sentinel:
      enabled: true
      transport:
        dashboard: 127.0.0.1:8849 # 连接dashboard
        port: 8719
  #服务名称
  application:
    name: ship-server
  datasource:
    url: jdbc:mysql://localhost/ship2?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#开启feign的降级
feign:
  hystrix:
    enabled: true

#mybaits配置
mybatis:
  type-aliases-package: org.example.shipserver.entity
  mapper-locations: classpath:mapper/*.xml

logging:
  file:
    name: logs/ship-server.log
    max-size: 20MB
    max-history: 1500
